"""Whisper language codes offered in the UI (subset; Whisper supports ~100)."""

LANGUAGES: dict[str, str] = {
    "es": "Español",
    "en": "Inglés",
    "zh": "Chino",
    "ja": "Japonés",
    "ko": "Coreano",
    "de": "Alemán",
    "fr": "Francés",
    "it": "Italiano",
    "pt": "Portugués",
    "ru": "Ruso",
    "ca": "Catalán",
    "gl": "Gallego",
    "eu": "Euskera",
    "nl": "Neerlandés",
    "pl": "Polaco",
    "tr": "Turco",
    "ar": "Árabe",
    "hi": "Hindi",
    "uk": "Ucraniano",
    "sv": "Sueco",
    "id": "Indonesio",
    "vi": "Vietnamita",
    "th": "Tailandés",
    "he": "Hebreo",
    "el": "Griego",
    "cs": "Checo",
}
